### PR TITLE
Suggested format changes

### PR DESCRIPTION
**Pull request by fapdash**
I've made some exemplary changes to the data model.
I'm opening this pull request so we can discuss.

- removed the quiz id:
  I'd suggest to model the database in a way that the categoryId == quizId, so there's no need to additionally track the quizId in the yaml file.
- removed the course id:
  Unless we want to have different quizzes if a category is used in multiple courses, we don't need to have the course id.
  The category id is enough.
- removed the question id:
  The question id has to be *globally unique* in the database, so the knowledgeforge has to assign them.
  My suggestion would be to write them back into the yaml and commit the file automatically once the knowledgeforge has loaded a question that didn't have a questionId yet.
- added `order` to question:
  Since the id can't be used any more to keep track of the order, an extra order field could be used for that.

Should the knowledgeforge delete quizzes and questions that get deleted from this repository?

### CODE REVIEW

**Comment by CHENHUI-XU** [comment]
Yes, thank you for your constructive advice, I will adjust accordingly.

As I understand Lars, he wants to manage Quiz completely in files. Therefore, I did not implement repository for Quizzes or Questions anymore. 

For every request, KnowledgeForge needs to pull (or automatically pull triggered by `Questions` repo commit) and access local files to serve quizzes and questions. So if I understand correctly, knowledgeforge does not need to delete quizzes or questions since KnowledgeForge did not store them initially.

So as for questionId, is it necessary to have QuestionId since we are not storing it into repository? Or it is configured that every class in knowledgeforge, stored in knoledgeforge repository or not, must have a unique Id?

**Comment by fapdash** [comment]
@CHENHUI-XU You don't have to adjust anything for now. I did a lot of changes yesterday to the code and these suggestions are the result of that.

If we actually don't use the database any more then my suggested changes might not be necessary. (especially the handling of the question id via knowledgeforge)

**Comment by vogella** [comment]
@fapdash I guess the assignment of the quizes to categories could be dynamically calculated based on the text file? In this case an update or change in the database should not be necessary.

**Comment by vogella** [comment]
The long term goal should be to reduce the usage of the data for the course content, so if possible we should keep the quizes out of the db. If it is currently required, I think this is also fine but my current thinking is that maintaining the course content via text files will be easier for me in the future.

**Comment by fapdash** [comment]
Do you want to also save and track the information about quiz answers etc. via yaml files / without the database?

A relational database gives us ACID guarantees, referential integrity, scaling.
If we decided to get rid of the database completely I think we'd have to implement transactions and referential integrity logic ourselves, if we don't want to eventually end up with messed up data, which would probably also be hard to debug.
This would also mean that user management and authorization would have to be handled by our home grown storage mechanism.
If we don't get rid of the database completely then the data in the YAML has to interact with data from the database at some point. (eg., an answer to a quiz question references a user)
I'd like to keep that interaction well isolated, at the edges of the application. This would mean that the application loads and syncs it's data model in the database with the yaml file(s), but otherwise handles persistence through the database.

**Comment by CHENHUI-XU** [comment]
@fapdash Since `Answer` is user related object, it should be complicated to handle as YAML files.

So my current design is to store `Answer` into database, which gives it a primary key as AnswerId. And the attributes `user`  + `questionId` will be unique to one `Answer`.

* user can be found by KnowledgeForge easily in query.
* for questionId, since we don't have questionId anymore, I redesigned into a string like `CategoryId-QuestionOrder`, which is also unique to one question.

Right now I am accessing files through KnowledgeForge to Git Repo, by `well isolated`, do you mean to access yaml files from Flutter? Or serve the yamls files from a different domain?

**Comment by vogella** [comment]
> Do you want to also save and track the information about quiz answers etc. via yaml files / without the database?

No, this should be stored in the database. But I don't think we need to store the individual answer of the user, only the score of a quiz should be stored. So maybe we need the quiz id in the database based on the yaml file and the user db entry say 45% in this quiz?

**Pull request merged**
